spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bag2bag_trade?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 20030304
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.bag2bag.st.entity
  configuration:
    map-underscore-to-camel-case: true